info:
  version: "@project.version@"
server:
  port: 8082
management:
  security:
    enabled: false   
spring:
  application:
    name: "@project.artifactId@"
  boot:
    admin:
      client:
        enabled: true
        prefer-ip: true
hystrix:
  metrics:
    enabled: true
feign:
  hystrix:
    enabled: true   ##需要开启此配置，不然不生效

    
