info:
  version: "@project.version@"
spring:
  application:
    name: "@project.artifactId@"
  cloud:
    config:
      enabled: false
    consul:
      host: 192.168.26.131
      port: 8500
      discovery:
        #tags: management.context-path=/foo, health.path=/ping
        health-check-interval: 10s
        health-check-timeout: 1s
#management.context-path: /foo
#endpoints.health.path: /ping
  boot:
    admin:
      routes:
        endpoints:
        - env
        - metrics
        - dump
        - jolokia
        - info
        - configprops
        - trace
        - logfile
        - refresh
        - flyway
        - liquibase
        - heapdump
        - loggers
        - auditevents
        - hystrix.stream
      turbine:
        clusters:
        - default
        location: service-monitor             ##指向我们定义的turbine server，这里本应用也是一个turbine server
spring.boot.admin.discovery:
  ignored-services: consul,service-monitor    ##不监控consul和自己本身
security:
  user:
    name: lucius
    password: 123456
turbine: ##定义自己本身是一个turbine server
  aggregator:
    clusterConfig: default   # 指定聚合哪些集群，多个使用","分割，默认为default。可使用http://.../turbine.stream?cluster={clusterConfig之一}访问
  appConfig: user-service    # 配置Consul中注册的serviceId列表，表明监控哪些服务
  clusterNameExpression: new String("default")
  # 1. clusterNameExpression指定集群名称，默认表达式appName；此时：turbine.aggregator.clusterConfig需要配置想要监控的应用名称
  # 2. 当clusterNameExpression: default时，turbine.aggregator.clusterConfig可以不写，因为默认就是default